# Generated by Django 4.2.2 on 2023-06-22 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('C', 'Completed'), ('F', 'Pending')], max_length=2)),
                ('date', models.DateField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('1', '1️⃣'), ('1', '2️⃣'), ('1', '3️⃣'), ('1', '4️⃣'), ('1', '5️⃣'), ('1', '6️⃣'), ('1', '7️⃣'), ('1', '8️⃣'), ('1', '9️⃣'), ('1', '🔟')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
